# NumPy Course - From Beginning to Advanced

# 1. INTRODUCTION

#### 1. The full form of NumPy is Numerical Python.
#### 2. It is used for faster calculations and matrix operations.
#### 3. Created by Travis Oliphant in 2005.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


#### The command above lets us install the NumPy library so we can use it for tasks like Data Analytics, Data Science, and much more. Just paste this command into your PowerShell to get started.

#### If it doesn’t work, we may need to install pip first. You can find the pip installation command on Google or simply ask any AI tool. And yes—using AI tools is not cheating. Myth busted!

#### After installing pip, then we can paste the give "pip install numpy" command now. Easy!

In [2]:
import numpy as np

#### This command is the starting point of our NumPy journey. It’s important because it enables NumPy in our working environment—whether that’s VS Code, Jupyter Notebook, or any other platform.

#### np isn’t strictly necessary to show that NumPy is imported—it’s just a convention to remind us that np refers to NumPy. You could use any name instead, as long as you don’t change the functions, operators, or specific symbols from the library.

### Well, that's enough theory, let's do some practical.

#### I already imported this library, so no need to write it over and over.

## Difference between Arrays and Lists

#### There i made a table below this code, for better visualization of Table Format, to make it easy how much Lists and Arrays are different from each other in Python.

In [3]:
from tabulate import tabulate  # For nice table formatting

# Data for the table (features are bolded using Markdown)
table = [
    ["***Space Requirement***", "Require less space", "Require more space"],
    ["***Efficiency for Numerical Operations***", "More efficient", "Less efficient"],
    ["***Speed for Mathematical Computations***", "Faster", "Slower"],
    ["***Dimensions***", "Can be multi-dimensional", "One-dimensional"],
    ["***Data Type Support***", "Single data type (homogeneous)", "Multiple data types (heterogeneous)"],
    ["***Memory Storage***", "Continuous memory blocks", "Scattered memory locations"],
    ["***Vectorization***", "Supports vectorized operations", "No vectorization, needs loops"],
    ["***Ease of Use***", "Requires NumPy knowledge", "Easier for beginners in Python"],
    ["***Performance for Large Data***", "High performance", "Low performance"],
    ["***Built-in Math Functions***", "Rich set of mathematical functions", "Fewer built-in math functions"]
]

# Column headers
headers = ["Feature", "Arrays (NumPy)", "Lists (Python)"]

# Display table in Jupyter (Markdown mode)
from IPython.display import Markdown
display(Markdown(tabulate(table, headers=headers, tablefmt="github")))


| Feature                                   | Arrays (NumPy)                     | Lists (Python)                      |
|-------------------------------------------|------------------------------------|-------------------------------------|
| ***Space Requirement***                   | Require less space                 | Require more space                  |
| ***Efficiency for Numerical Operations*** | More efficient                     | Less efficient                      |
| ***Speed for Mathematical Computations*** | Faster                             | Slower                              |
| ***Dimensions***                          | Can be multi-dimensional           | One-dimensional                     |
| ***Data Type Support***                   | Single data type (homogeneous)     | Multiple data types (heterogeneous) |
| ***Memory Storage***                      | Continuous memory blocks           | Scattered memory locations          |
| ***Vectorization***                       | Supports vectorized operations     | No vectorization, needs loops       |
| ***Ease of Use***                         | Requires NumPy knowledge           | Easier for beginners in Python      |
| ***Performance for Large Data***          | High performance                   | Low performance                     |
| ***Built-in Math Functions***             | Rich set of mathematical functions | Fewer built-in math functions       |

 # 2. ARRAY CREATION

### 1. Creating an Array

In [4]:
list1 = [1,2,3,4,5,6,7,8,9,10] # list of numbers
array1 = np.array(list1) # converting list to array
print(array1) # printing the array

[ 1  2  3  4  5  6  7  8  9 10]


### 2. Creating Zero Matrix

In [5]:
np.zeros((3, 4)) # creating a 3x4 array of zeros. 3 Rows and 4 Columns.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3. Creating Ones Matrix

In [6]:
np.ones((3, 4)) # creating a 3x4 array of ones. 3 Rows and 4 Columns.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 4. Random Matrix

In [7]:
np.random.rand(3, 4) # creating a 3x4 array of random numbers. 3 Rows and 4 Columns of number between 0 and 1 only.

array([[0.47607224, 0.49445318, 0.91831338, 0.2126603 ],
       [0.73438467, 0.45393354, 0.35303008, 0.26336162],
       [0.8364499 , 0.50167396, 0.50475309, 0.48244048]])

### 5. Arange Array of Numbers

In [8]:
np.arange(10) # creating an array of numbers from 0 to 9.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 6. Linespace

In [9]:
np.linspace(0, 1, 5) # creating an array of 5 numbers evenly spaced between 0 and 1.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 7. Identity Matrix

In [10]:
np.eye(3) # creating a 3x3 identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8. Diagonal Matrix

In [11]:
np.diag(np.array([1, 2, 3])) # creating a diagonal matrix with the given array as the diagonal elements.

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 9. Empty Array

In [12]:
np.empty((3, 4)) # creating an empty array of shape 3x4. The values are not initialized and can be anything.

array([[0.47607224, 0.49445318, 0.91831338, 0.2126603 ],
       [0.73438467, 0.45393354, 0.35303008, 0.26336162],
       [0.8364499 , 0.50167396, 0.50475309, 0.48244048]])

# 3. DATATYPES AND ATTRIBUTES

## Data Types

In [13]:
list1 = [1,2,3,4,5,6,7,8,9]
array1 = np.array(list1)
print(array1)

print(array1.dtype) # Displaying the data type of the array elements

print(array1.astype(float)) # Converting the array to float type

[1 2 3 4 5 6 7 8 9]
int64
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Array Attributes

### Let's set an array for further uses in Attributes of NumPy array.

In [14]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 1. Shape

In [15]:
a.shape # It shows the shape of the array, which is (2, 5) meaning 2 rows and 5 columns.

(2, 5)

### 2. Size

In [16]:
a.size # It shows the total number of elements in the array, which is 10 in this case.

10

### 3. Number of Dimensions

In [17]:
a.ndim # It shows the number of dimensions of the array, which is 2 for a 2D array.

2

### 4. Item Size

In [18]:
a.itemsize 

8

### 5. Number of Bytes

In [19]:
a.nbytes

80

# 4. INDEXING AND SLICING

### 1. Basic Indexing

#### I can access elements in a NumPy array just like in Python lists, but it also supports multi-dimensional indexing.

In [20]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Accessing the first element of the array
print(arr[-1])  # Accessing the last element of the array

10
50


In [21]:
arr1 = np.array([[10, 20, 30],[40, 50, 60]])
print(arr1[0, 0])  # Accessing the first element of the first row
print(arr1[1, 2])  # Accessing the third element of the second row

10
60


### 2. Slicing

#### 1D Slicing

In [22]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])  # Slicing elements from index 1 to 3 (exclusive of 4)
arr[0:]  # Slicing from the start to the end of the array
print(arr[:])  # Slicing the entire array
print(arr[1::2])  # Slicing every second element of the array

[20 30 40]
[10 20 30 40 50 60]
[20 40 60]


#### 2D Slicing

In [23]:
arr1 = np.array([[10, 20, 30],[40, 50, 60]])
print(arr1[0, :])  # Accessing the first row
print(arr1[:, 1])  # Accessing the second column
print(arr1[0:2, 1:3])  # Slicing a sub-array from the first two rows and the second and third columns

[10 20 30]
[20 50]
[[20 30]
 [50 60]]


### 3. Boolean Indexing

In [24]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr <= 30)  # Boolean indexing to check which elements are less than or equal to 30
print(arr[arr <= 30])  # Accessing elements that are less than or equal to 30

[ True  True  True False False False]
[10 20 30]


### 4. Fancy Indexing

#### 1D Fancy Indexing

In [25]:
arr = np.array([10, 20, 30, 40, 50, 60])
indexes = [0, 2, 4]
print(arr[indexes])  # Accessing elements at specific indices

[10 30 50]


#### 2D Fancy Indexing

In [26]:
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2d[[0, 2]])  # Rows 0 and 2

[[1 2]
 [5 6]]


### 5. Copy vs View

In [27]:
arr = np.array([1, 2, 3, 4])
slice_view = arr[1:3]  # View
slice_view[0] = 100
print(arr)  # [  1 100   3   4]  # Original changed

arr_copy = arr[1:3].copy()  # Copy
arr_copy[0] = 200
print(arr)  # [  1 100   3   4]  # No change

[  1 100   3   4]
[  1 100   3   4]


# 5. ARRAY OPERATIONS

### 1. Arithmetic Operators

In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** 2)
print(arr1 % 3)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 1  4  9 16 25]
[1 2 0 1 2]


### 2. Scalar Operations

In [29]:
arr = np.array([1,2,3])
print(arr + 10)
print(arr * 2)

[11 12 13]
[2 4 6]


### 3. Logical Operations

In [30]:
arr = np.array([10,20,30,40,50])
print(arr > 25)

[False False  True  True  True]


#### Bonus

In [31]:
np.greater(arr, 25)
np.less(arr, 25)
np.equal(arr, 25)

array([False, False, False, False, False])

### 4. Broadcast Operators

In [32]:
arr = np.array([1, 2, 3])
matrix = np.array([[10, 20, 30],[40, 50, 60]])

print(matrix + arr)


[[11 22 33]
 [41 52 63]]


### 5. In-Place Operations

In [33]:
arr = np.array([1, 2, 3])
arr += 5
print(arr)

[6 7 8]


# 6. UNIVERSAL FUNCTIONS(ufuncs)

### 

Why ufuncs?

1. Speed: Operates at C speed, no Python loops.
2. Element-wise operations: Apply on entire arrays at once.
3. Supports broadcasting: Works on arrays of different shapes.
4. Supports optional parameters: e.g., out, where.

Types of ufuncs

1. Binary ufuncs – Operate on two arrays.
Examples: np.add(), np.subtract(), np.multiply(), np.divide()

2. Unary ufuncs – Operate on one array.
Examples: np.sqrt(), np.exp(), np.abs()

### 1. Binary ufuncs

In [34]:
arr = np.array([1, 2, 3, 4, 5])

np.add(arr, 5)  # Adding 5 to each element of the array

array([ 6,  7,  8,  9, 10])

In [35]:
np.subtract(arr, 2)  # Subtracting 2 from each element of the

array([-1,  0,  1,  2,  3])

In [36]:
np.multiply(arr, 3)  # Multiplying each element by 3

array([ 3,  6,  9, 12, 15])

In [37]:
np.divide(arr, 2)  # Dividing each element by 2

array([0.5, 1. , 1.5, 2. , 2.5])

### 2. Unary ufuncs

In [38]:
arr1 = np.array([1, 4, 9, 16, 25])

np.sqrt(arr1)  # Square root of each element

array([1., 2., 3., 4., 5.])

In [39]:
np.exp(arr1)  # Exponential of each element. It calculates e raised to the power of each element.

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [40]:
np.abs(arr1)  # Absolute value of each element. It returns the non-negative value of each element.

array([ 1,  4,  9, 16, 25])

In [41]:
np.log(arr1)  # Natural logarithm of each element. Its undefined for non-positive values.

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

### Some other Mathematical ufuncs

In [42]:
np.power(arr1, 2)  # Squaring each element. Raises each element to the power of 2.

array([  1,  16,  81, 256, 625])

In [43]:
np.mod(arr1, 3)  # Modulus of each element with 3. Returns the remainder when each element is divided by 3.

array([1, 1, 0, 1, 1])

In [44]:
np.sign(arr1)  # Sign of each element: -1 for negative, 0 for zero, 1 for positive

array([1, 1, 1, 1, 1])

In [45]:
np.floor(arr1) # Floor of each element. It rounds down to the nearest integer.

array([ 1,  4,  9, 16, 25])

In [46]:
np.ceil(arr1)  # Ceiling of each element. It rounds up to the nearest integer.

array([ 1,  4,  9, 16, 25])

# 7. NUMPY FOR STATISTICS

In [47]:
arr1 = [1,2,3,4,5,6,7,8,9,10]

### 1. Basic Descriptive Statistics

In [48]:
np.mean(arr1)  # Mean (average) of the array elements

np.float64(5.5)

In [49]:
np.median(arr1)  # Median (middle value) of the array elements

np.float64(5.5)

In [ ]:
np.std(arr1) # Standard deviation of the array elements

np.float64(2.8722813232690143)

In [52]:
np.var(arr1) # Variance of the array elements

np.float64(8.25)

### 2. Percentiles and Quantiles

In [53]:
np.percentile(arr1, 25)  # 25th percentile of the array elements

np.float64(3.25)

In [54]:
np.percentile(arr1, 50)  # 50th percentile (median)

np.float64(5.5)

In [55]:
np.percentile(arr1, 75)  # 75th percentile (median)

np.float64(7.75)

### 3. Correlation & Covariance

In [57]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

In [58]:
print(np.corrcoef(x, y))  # Correlation coefficient matrix

[[1. 1.]
 [1. 1.]]


In [59]:
print(np.cov(x, y))  # Covariance matrix

[[ 2.5  5. ]
 [ 5.  10. ]]
